name: rhometa
channels:
  - conda-forge
  - bioconda
dependencies:
  - 'python=3.12'
  - 'numpy=1.26'
  - 'pandas=2.2'
  - 'scipy=1.14'
  - 'seaborn=0.13'
  - 'numba'
  - 'tqdm=4.66'
  - 'bcftools=1.18'
  - 'bwa-mem2=2.2.1'
  - 'pysam=0.22'
  - 'fastp=0.23.4' 
  - 'freebayes=1.3.6'
  - 'samtools=1.18'
  - 'angsd=0.940'
  - 'openssl'
  - 'ncurses'